version: "3.7"

networks:
    nelson-net:
        name: nelson-net
        driver: bridge

volumes:
    postgres-data:

services:
    web:
        image: nginx:latest
        container_name: glfinder-nginx
        hostname: glfinder-nginx
        expose:
            - 80
        networks:
            - nelson-net
        volumes:
            - "./web:/web"
            - "./configs/site.conf:/etc/nginx/conf.d/default.conf"
            - "./configs/nginx.conf:/etc/nginx/nginx.conf"
            - "./configs/bots.d/:/etc/nginx/bots.d/"
            - "./configs/globalblacklist.conf:/etc/nginx/conf.d/globalblacklist.conf"
            - "./configs/botblocker-nginx-settings.conf:/etc/nginx/conf.d/botblocker-nginx-settings.conf"
        links:
            - php
        restart: always
        labels:
          - "com.centurylinklabs.watchtower.enable=true"

    php:
        build: ./php
        image: glfinder-php:latest
        container_name: glfinder-php
        hostname: glfinder-php
        networks:
            - nelson-net
        volumes:
            - "./web:/web"
        restart: always

    feeder:
        build: ./feeder
        image: glfinder-feeder:latest
        container_name: glfinder-feeder
        hostname: glfinder-feeder
        networks:
            - nelson-net
        expose:
            - 5000
        restart: always

    database:
        image: postgres:12
        container_name: glfinder-db
        hostname: glfinder-db
        networks:
            - nelson-net
        env_file:
            - configs/postgres.env
        volumes:
            - "postgres-data:/var/lib/postgresql/data"
        restart: always
        labels:
          - "com.centurylinklabs.watchtower.enable=true"

    api:
        build: api/
        image: glfinder-api:latest
        container_name: glfinder-api
        hostname: glfinder-api
        networks:
            - nelson-net
        expose:
            - 8080
        env_file:
            - configs/postgres.env
        environment:
            - FLASK_APP=main.py
        depends_on:
            - database
        restart: always
